book_ex/urls.py
from django.contrib import admin
from django.urls import path
from book_ex import views


app_name='book_ex'

urlpatterns = [
    path('bookex_form/', views.bookex_form, name='bookex_form'),
    path('near_book', views.near_book, name='near_book'),
    path('map_near_book/', views.map_near_book, name='map_near_book'),
]

core/urls.py
from django.urls import path
from core import views
app_name = 'core'

urlpatterns = [
    path('search_by_name', views.search_by_name, name='search_by_name'),
    path('search_by_genre', views.search_by_genre, name='search_by_genre'),
    path('search_by_author', views.search_by_author, name='search_by_author'),
    path('search_by_similarUser', views.search_by_similarUser, name='search_by_similarUser'),
    path('book_details', views.book_details, name='book_details'),
    path('user_login',views.user_login,name='user_login'),
    path('user_register',views.user_register,name='user_register'),
    #url(r'^base/$', views.base, name='base'),
]

donation/urls.py
from django.contrib import admin
from django.urls import path
from donation import views


app_name='donation'

urlpatterns = [
     #path('', views.index, name='index'),
     path('nearby/', views.nearby, name='nearby'),
     path('map_near_ngo/', views.map_near_ngo, name='map_near_ngo'),
     path('ngo_form/', views.ngo_form, name='ngo_form'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('message/', views.message,name='message'),
    path('about',views.about,name='about'),
    path('core/', include('core.urls')),
    path('book_ex/', include('book_ex.urls')),
    path('web_scrape/', include('web_scrape.urls')),
    path('donation/', include('donation.urls')),
    path('profile',views.profile,name='profile'),
    path('logout',views.user_logout,name='user_logout'),
]

book_ex/models.py
from django.contrib.gis.db import models

class Book_ex(models.Model):
    name = models.CharField(max_length=100)
    location = models.PointField()
    address = models.CharField(max_length=150)
    city = models.CharField(max_length=50)
    book= models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    email= models.EmailField(max_length = 254)
    contact= models.CharField(max_length=20)
    genre= models.CharField(max_length=120)

book_ex/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from core.models import UserProfileInfo, Book, Author, Genre
from .models import Book_ex
from django.contrib.gis.geos import Point
from django.contrib.gis.measure import D
from django.contrib.gis.geos import fromstr
from django.contrib.gis.db.models.functions import Distance
import folium
from core.views import message


# CREATING NEW BOOK NODE
def createBookNode(Title, img_url, genre, author):
    bookNode = Book(Title=Title, img_url=img_url, rating=0).save()

    if not Author.nodes.get_or_none(name=author):
        Author(name=author).save()
    authorNode = Author.nodes.get(name=author)

    genreNode = Genre.nodes.get(name=genre)

    authorNode.wrote.connect(bookNode)
    genreNode.bookGenre.connect(bookNode)


# BOOK EXCHANGE FORM
def bookex_form(request):
    name=""
    address=""
    city=""
    lat=0.0
    long=0.0
    book=""
    img_url=""
    author=""
    email=""
    contact=""
    details=False

    if request.method == 'POST' and details==False:
        details=True
        name = request.POST.get('name')
        address= request.POST.get('address')
        city= request.POST.get('city')
        lat=request.POST.get('lat')
        long=request.POST.get('long')
        book= request.POST.get('book')
        img_url=request.POST.get('img_url')
        author=request.POST.get('author')
        email=request.POST.get('email')
        contact=request.POST.get('contact')
        genre=request.POST.get('genre')

        location = fromstr(f'POINT({long} {lat})', srid=4326)

        bookNode = Book.nodes.get_or_none(Title=book)
        if not bookNode:
            createBookNode(Title=book, img_url=img_url, genre=genre, author=author)

        s=Book_ex(name=name, location=location, address=address, city=city, book=book,author=author, email=email, contact=contact, genre=genre)
        #print(type(s))
        s.save()
        return message(request,'Thank you for submitting your details!')

    genreNodes = Genre.nodes.all()
    return render(request,'book_ex/bookex_form.html', {"genres":genreNodes})


# finding the nearby users with book req by curr user
def near_book(request):
    if request.POST.get('exchange'):
        bookTitle = request.POST.get('exchange')
        return render(request, 'book_ex/near_book.html', {"book":bookTitle})

    else:
        lat=0.0
        long=0.0
        dist=""
        near=[]
        dirn=[]

        lat=request.POST.get('lat')
        long=request.POST.get('long')
        location = fromstr(f'POINT({long} {lat})', srid=4326)

        dist=request.POST.get('dist')
        print(location)
        book=request.POST.get('book')
        bookTitle=request.POST.get('book')
        print(book)
        if dist=="lt1":
            near = Book_ex.objects.annotate(distance=Distance("location", location)/1000).filter(distance__lte=1, book=book).order_by("distance")
        elif dist=="lt5":
            near = Book_ex.objects.annotate(distance=Distance("location", location)/1000).filter(distance__lte=5, book=book).order_by("distance")
        elif dist=="lt10":
            near= Book_ex.objects.annotate(distance=Distance("location", location)/1000).filter(distance__lte=10, book=book).order_by("distance")
        else:
            near= Book_ex.objects.annotate(distance=Distance("location", location)/1000).filter(distance__lte=15, book=book).order_by("distance")
        
        print(near)
        
        m=folium.Map(location=[lat,long],zoom_start=12)

        folium.Marker(
            [lat,long],
            popup='',
            tooltip='Your Location!',
            icon=folium.Icon(color='red')
        ).add_to(m),

        if len(near)>0:
            for book in near:
                org_address=book.address.replace(' ','+')
                link="https://www.google.com/maps/dir/?api=1&destination=" + org_address
                dirn.append(link)
                tooltip="Name:"+book.name+" , Email:"+book.email+" , Contact:"+book.contact
                folium.Marker(
                    [book.location.y,book.location.x],
                    popup='<a href="' + link + '">GetDirection</a>',
                    tooltip=tooltip
                ).add_to(m)

                m.save('templates/book_ex/map_near_book.html')

        return render(request,'book_ex/near_book.html',{'near':near, 'dirn':dirn,'zip':zip(near,dirn),'book':bookTitle, 'submitted':True})
    

# Showing the user and result on map
def map_near_book(request):
    return render(request,'book_ex/map_near_book.html')

templates/book_ex/bookex_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title> Book Exchange Form  </title>
      <!-- Favicon -->
      <link rel="icon" href="{% static 'assets/images/favicon.png' %}" type="image/x-icon" />
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
      <!-- footer CSS -->
      <link rel="stylesheet" href="{% static 'assets/css/footer.css' %}">
      <!-- Animate CSS -->
      <link href="{% static 'assets/vendors/animate/animate.css' %}" rel="stylesheet">
      <!-- Icon CSS-->
      <link rel="stylesheet" href="{% static 'assets/vendors/font-awesome/css/font-awesome.min.css' %}">
      <!-- Camera Slider -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Camera/1.3.4/css/camera.css">
      <!-- Owlcarousel CSS-->
      <link rel="stylesheet" type="text/css" href="{% static 'assets/vendors/owl_carousel/owl.carousel.css' %}" media="all">
      <!--Template Styles CSS-->
      <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}" media="all" />
      <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,600,600i,700,700i,800,800i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese" rel="stylesheet">
   </head>
   <body id="top">
      <div class="about-bg-banner-img">
         <div class="overlay-all ">
        
          <nav class="header-nav">
            <div class="header-nav__content">
               <h3 style="font-size:1vw">Sha-Fi-Rec-Do </h3>
               <ul class="header-nav__list">
                  <li class=""><a class=""  href="{% url 'index' %}" >Home</a></li>
                  <li><a class=""  href="{% url 'about' %}" >About</a></li>
                  {% if user.is_authenticated %}
                  <li><a>Search</a></li>
                      <ul class="list-group">
                          <a href="{% url 'core:search_by_name' %}" style="margin-left: 20px;">1. By Name </a>
                          <a href="{% url 'core:search_by_genre' %}" style="margin-left: 20px;">2. By Genre</a>
                          <a href="{% url 'core:search_by_author' %}" style="margin-left: 20px;">3. By Author</a>
                      </ul>

                  <li><a>Get Recommendation</a></li>
                      <ul class="list-group">
                          <a href="{% url 'core:search_by_similarUser' %}" style="margin-left: 20px;">1. Read by Similar User</a>
                      </ul>

                  <li><a>Book Exchange</a></li>
                     <ul class="list-group">
                        <a href="{% url 'book_ex:bookex_form' %}" style="margin-left: 20px;">1. Exchange Your Book</a>
                        
                        <a href="{% url 'core:search_by_name' %}" style="margin-left: 20px;">2. Search Book for Exchange</a>
                     </ul>
                  <li><a class=""  href="{% url 'donation:nearby' %}">Donate</a></li>
                  <li><a class=""  href="{% url 'donation:ngo_form' %}">Register NGO </a></li>
                  
                  
                  <li><a class=""  href="{% url 'profile' %}">Profile</a></li>
                  <li><a class=""  href="{% url 'user_logout' %}">Logout</a></li>
                  {% else %}
                     <li><a class=""  href="{% url 'core:user_login' %}">Login </a></li>
                     <li><a class=""  href="{% url 'core:user_register' %}">Register</a></li>
                  {% endif %}
                  
               </ul>
               
            </div>
            <!-- end header-nav__content -->
         </nav>
               <!-- end header-nav -->
               <a class="header-menu-toggle" href="#0">
               <span class="header-menu-icon"></span>
               </a>
            </header>
            <!-- end s-header -->
            <!-- End Header_Area -->
            <!-- #banner start -->
            <section id="banner" class="py_120">
               <div class="container ">
                  <div class="row">
                     <!-- #banner-text start -->            
                     <div id="banner-text" class="col-md-7 text-c text-left ">
                        <h5 class="wow fadeInUp main-h font_30" data-wow-delay="0.2s" > Want to exchange your book ?
                           <!-- <br><span class="about_text "> CONTACT US </span>  -->
                        </h5>
                     
                     </div>
                     <!-- /#banner-text End -->
                  </div>
               </div>
            </section>
            <!--#Our banner-shap- Area -->
            <div class="container-fluid p0 banner-shap-img">
            </div>
            <!--#EndOur banner-shap- Area -->
         </div>
      </div>
      <!-- /#banner end -->
      
      
      <div class="container">

        <br>
        
            <h1>Give your details to be eligible for book exchange!</h1>
          <br>
          <button style="margin-left:10px" onclick="getlocation()">Click me to get your location</button>
          <br>
          <div class="container pt-4">
            <form method="post">
              {% csrf_token %}
              <div class="form-group">
                <label for="book">Latitude</label>
                <input type="text" class="form-control col-6" id="lat" name="lat" aria-describedby="emailHelp">
              </div>
        
              <div class="form-group">
                <label for="book">Longitude</label>
                <input type="text" class="form-control col-6" id="long" name="long" aria-describedby="emailHelp">
              </div>
        
                <div class="form-group">
                  <label for="book">Name</label>
                  <input type="text" class="form-control col-6" id="name" name="name" aria-describedby="emailHelp">
        
                </div>
        
                <div class="form-group">
                  <label for="book">City</label>
                  <input type="text" class="form-control col-6" name="city" aria-describedby="emailHelp">
        
                </div>
        
                <div class="form-group">
                  <label for="book">Address</label>
                  <input type="text" class="form-control col-6" name="address" aria-describedby="emailHelp">
        
                </div>
        
                <div class="form-group">
                  <label for="book">Book Title</label>
                  <input type="text" class="form-control col-6" name="book" aria-describedby="emailHelp">
                </div>

                <div class="form-group">
                  <label for="book">Book Image URL</label>
                  <input type="text" class="form-control col-6" name="img_url" aria-describedby="emailHelp">
                </div>
        
                <div class="form-group">
                  <label for="book">Author</label>
                  <input type="text" class="form-control col-6" name="author" aria-describedby="emailHelp">
        
                </div>
        
                <div class="form-group">
                  <label for="book">Genre</label>
                  <select name="genre" class="form">
                    <option disabled selected>Select Genre</option>
                  {% for g in genres %}
                      <option value="{{ g.name }}">{{ g.name }}</option>
                  {% endfor %}
                  </select>
                  
        
                </div>
        
                <div class="form-group">
                  <label for="book">Email</label>
                  <input type="text" class="form-control col-6" name="email" aria-describedby="emailHelp">
        
                </div>
        
                <div class="form-group">
                  <label for="book">Contact</label>
                  <input type="text" class="form-control col-6" name="contact" aria-describedby="emailHelp">
        
                </div>
        <br>
        
        
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
        <br><br>
        
        </div>
        
        <script>
          var x = document.getElementById("lat");
          var y = document.getElementById("long");
        
          function getlocation() {
            if (navigator.geolocation) {
              navigator.geolocation.getCurrentPosition(showPosition)
            } else {
              alert("Sorry! your browser is not supporting")
            }
          }
        
          function showPosition(position) {
            var x = position.coords.latitude;
            var y = position.coords.longitude;        
        
            document.getElementById("lat").value = x;
            document.getElementById("long").value = y;
          }
        </script>

            <!--#start Our footer Area -->
            <section id="footer">
              <div class="container">
                 <div class="row text-center text-xs-center text-sm-left text-md-left">
                    <div class="col-xs-12 col-sm-4 col-md-4">
                       <h5>Quick links</h5>
                       <ul class="list-unstyled quick-links">
                          <li><a href="#"><i class="fa fa-angle-double-right"></i>Home</a></li>
                          <li><a href="#"><i class="fa fa-angle-double-right"></i>About</a></li>
                          <li><a href="#"><i class="fa fa-angle-double-right"></i>Search</a></li>
                          <li><a href="#"><i class="fa fa-angle-double-right"></i>Login</a></li>
                          <li><a href="#"><i class="fa fa-angle-double-right"></i>Register</a></li>
                       </ul>
                    </div>
                    <div class="col-xs-12 col-sm-4 col-md-4">
                       <h5>Contact Us</h5>
                       <ul class="list-unstyled quick-links">
                          <li><a href="#"><i class="fa fa-phone"></i>+91 1234567890</a></li>
                          <li><a href="#"><i class="fa fa-envelope"></i>shafiredo@gmail.com</a></li>
                       </ul>
                    </div>
                    <div class="col-xs-12 col-sm-4 col-md-4">
                       <h5>Address</h5>
                       <ul class="list-unstyled quick-links">
                          <li><a href="#"><i class="fa fa-location"></i>Mumbai,India</a></li>
                       </ul>
                    </div>
                 </div>
                 <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-5">
                      
                    </div>
                    <hr>
                 </div>	
                 <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
                       <p class="h6">© All right Reversed.<a class="text-green ml-2" href="#" target="_blank">ShaFeReDo</a></p>
                    </div>
                    <hr>
                 </div>	
              </div>
           </section>
        
      
      <!-- /.hero__overlay -->
      <!-- jQuery JS -->
      <script src="{% static 'assets/js/jquery-1.12.0.min.js' %}"></script>
      <script src="{% static 'assets/vendors/popup/lightbox.min.js' %}"></script>
      <script type="text/javascript">
         $(document).ready(function() {
         $("div.bhoechie-tab-menu>div.list-group>a").click(function(e) {
           e.preventDefault();
           $(this).siblings('a.active').removeClass("active");
           $(this).addClass("active");
           var index = $(this).index();
           $("div.bhoechie-tab>div.bhoechie-tab-content").removeClass("active");
           $("div.bhoechie-tab>div.bhoechie-tab-content").eq(index).addClass("active");
         });
         });
      </script> 
      
      <script type="text/javascript">
         $(document).ready(function () {
             $('#sidebarCollapse').on('click', function () {
                 $('#sidebar').toggleClass('active');
                 $(this).toggleClass('active');
             });
         });
      </script>
      <!-- Bootstrap JS -->
      <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
      <!-- Animate JS -->
      <script src="{% static 'assets/vendors/animate/wow.min.js' %}"></script>
      <script src="{% static 'assets/vendors/sidebar/main.js' %}"></script>
      <!-- Owlcarousel JS -->
      <script src="{% static 'assets/vendors/owl_carousel/owl.carousel.min.js' %}"></script>
      <!-- Stellar JS-->
      <!-- Theme JS -->
      <script src="{% static 'assets/js/theme.min.js' %}"></script>
      
   </body>
</html>

templates/book_ex/near_book.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title> Contact Page  </title>
      <!-- Favicon -->
      <link rel="icon" href="{% static 'assets/images/favicon.png' %}" type="image/x-icon" />
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
      <!-- Animate CSS -->
      <link href="{% static 'assets/vendors/animate/animate.css' %}" rel="stylesheet">
      <!-- Icon CSS-->
      <link rel="stylesheet" href="{% static 'assets/vendors/font-awesome/css/font-awesome.min.css' %}">
      <!-- Camera Slider -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Camera/1.3.4/css/camera.css">
      <!-- Owlcarousel CSS-->
      <link rel="stylesheet" type="text/css" href="{% static 'assets/vendors/owl_carousel/owl.carousel.css' %}" media="all">
      <!--Template Styles CSS-->
      <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}" media="all" />
      <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,600,600i,700,700i,800,800i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese" rel="stylesheet">
   </head>
   <body id="top">
      <div class="about-bg-banner-img">
         <div class="overlay-all ">
        
            <nav class="header-nav">
               <div class="header-nav__content">
                  <h3 style="font-size:1vw">Sha-Fi-Rec-Do </h3>
                  <ul class="header-nav__list">
                     <li class=""><a class=""  href="{% url 'index' %}" >Home</a></li>
                     <li><a class=""  href="{% url 'about' %}" >About</a></li>
                     {% if user.is_authenticated %}
                     <li><a>Search</a></li>
                         <ul class="list-group">
                             <a href="{% url 'core:search_by_name' %}" style="margin-left: 20px;">1. By Name </a>
                             <a href="{% url 'core:search_by_genre' %}" style="margin-left: 20px;">2. By Genre</a>
                             <a href="{% url 'core:search_by_author' %}" style="margin-left: 20px;">3. By Author</a>
                         </ul>

                     <li><a>Get Recommendation</a></li>
                         <ul class="list-group">
                             <a href="{% url 'core:search_by_similarUser' %}" style="margin-left: 20px;">1. Read by Similar User</a>
                         </ul>

                     <li><a>Book Exchange</a></li>
                        <ul class="list-group">
                           <a href="{% url 'book_ex:bookex_form' %}" style="margin-left: 20px;">1. Exchange Your Book</a>
                           
                           <a href="{% url 'core:search_by_name' %}" style="margin-left: 20px;">2. Search Book for Exchange</a>
                        </ul>
                     <li><a class=""  href="{% url 'donation:nearby' %}">Donate</a></li>
                     <li><a class=""  href="{% url 'donation:ngo_form' %}">Register NGO </a></li>
                     
                     
                     <li><a class=""  href="{% url 'profile' %}">Profile</a></li>
                     <li><a class=""  href="{% url 'user_logout' %}">Logout</a></li>
                     {% else %}
                        <li><a class=""  href="{% url 'core:user_login' %}">Login </a></li>
                        <li><a class=""  href="{% url 'core:user_register' %}">Register</a></li>
                     {% endif %}
                     
                  </ul>
                  
               </div>
               <!-- end header-nav__content -->
            </nav>
               <!-- end header-nav -->
               <a class="header-menu-toggle" href="#0">
               <span class="header-menu-icon"></span>
               </a>
            </header>
            <!-- end s-header -->
            <!-- End Header_Area -->
            <!-- #banner start -->
            <section id="banner" class="py_120">
               <div class="container ">
                  <div class="row">
                     <!-- #banner-text start -->            
                     <div id="banner-text" class="col-md-7 text-c text-left ">
                        <h5 class="wow fadeInUp main-h font_30" data-wow-delay="0.2s" > Find people near you to get your favourite book!
                           <!-- <br><span class="about_text "> CONTACT US </span>  -->
                        </h5>
                     
                     </div>
                     <!-- /#banner-text End -->
                  </div>
               </div>
            </section>
            <!--#Our banner-shap- Area -->
            <div class="container-fluid p0 banner-shap-img">
            </div>
            <!--#EndOur banner-shap- Area -->
         </div>
      </div>
      <!-- /#banner end -->
      
      <div class="container">
        <br>
      
      
        <h1>Find nearest users for exchanging books!</h1>
        <button style="margin-left:10px" onclick="getlocation()">Click me to get your location</button>
        <br>
        <div class="container pt-4">
          <form method="post">
            {% csrf_token %}
            <div class="form-group">
              <label for="book">Latitude</label>
              <input type="text" class="form-control col-6" id="lat" name="lat" aria-describedby="emailHelp">
            </div>
      
            <div class="form-group">
              <label for="book">Longitude</label>
              <input type="text" class="form-control col-6" id="long" name="long" aria-describedby="emailHelp">
            </div>
      
            <div class="form-group">
              <label for="book">Select a Distance Range</label>
      
              <select name="dist">
                <option value="lt1">less than 1 km</option>
                <option value="lt5">less than 5 km</option>
                <option value="lt10">less than 10 km</option>
                <option value="lt15">less than 15 km</option>
              </select>
            </div>
      
            <button type="submit" class="btn btn-primary" name="book" value="{{ book }}">Submit</button>
          </form>
        </div>
    



    {% if submitted %}
    <h3 style="display:inline-block; margin-right:20px">Your Results! </h3> <a style="background:blue;" href="{% url 'book_ex:map_near_book' %}"> View Results on map </a>
    
    {% if near %}
    <table class="table table-bordered">

      <thead>
        <th>Name</th>
        <th>Address</th>
        <th>Book Title</th>
        <th>Email</th>
        <th>Contact</th>
        <th>Distance</th>
        <th>Directions</th>
      </thead>

      {% for usr,direction in zip %}
      <tr>
        <td>{{ usr.name }}</td>
        <td>{{ usr.address }}</td>
        <td>{{ book }}</td>
        <td>{{ usr.email }}</td>
        <td>{{ usr.contact }}</td>
        <td>{{ usr.distance|stringformat:".6s" }} km</td>
        <td><a href="{{ direction }}"><img src="{% static 'assets/images/map.png' %}" width="20" height="30"></a></td>
      </tr>
      {% endfor %}

    </table>

    {% else %}
    <p>No results found! Try a different book!</p>

    {% endif %}

    <!--#start Our footer Area -->
    <div class="our_footer_area">
        <div class="book_now_aera ">
            <div class="container wow fadeInUp">
            <div class="row book_now">
                <div class="col-md-4">
                    <div class="">
                        
                    </div>
                    
                    
                </div>
                <div class="col-md-1 ">
                </div>
                <div class="col-md-3">
                    
                    
                </div>
                <div class="col-md-4">
                    
                </div>
                <div class="col-md-12">
                    
                </div>
            </div>
            </div>
        </div>
    </div>
    
    {% endif %}


    <script>
      var x = document.getElementById("lat");
      var y = document.getElementById("long");
    
      function getlocation() {
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(showPosition)
        } else {
          alert("Sorry! your browser is not supporting")
        }
      }
    
      function showPosition(position) {
        var x = position.coords.latitude;
        var y = position.coords.longitude;        
    
        document.getElementById("lat").value = x;
        document.getElementById("long").value = y;
      }
    </script>
            
        
        
      
      <!-- /.hero__overlay -->
      <!-- jQuery JS -->
      <script src="{% static 'assets/js/jquery-1.12.0.min.js' %}"></script>
      <script src="{% static 'assets/vendors/popup/lightbox.min.js' %}"></script>
      <script type="text/javascript">
         $(document).ready(function() {
         $("div.bhoechie-tab-menu>div.list-group>a").click(function(e) {
           e.preventDefault();
           $(this).siblings('a.active').removeClass("active");
           $(this).addClass("active");
           var index = $(this).index();
           $("div.bhoechie-tab>div.bhoechie-tab-content").removeClass("active");
           $("div.bhoechie-tab>div.bhoechie-tab-content").eq(index).addClass("active");
         });
         });
      </script> 
      
      <script type="text/javascript">
         $(document).ready(function () {
             $('#sidebarCollapse').on('click', function () {
                 $('#sidebar').toggleClass('active');
                 $(this).toggleClass('active');
             });
         });
      </script>
      <!-- Bootstrap JS -->
      <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
      <!-- Animate JS -->
      <script src="{% static 'assets/vendors/animate/wow.min.js' %}"></script>
      <script src="{% static 'assets/vendors/sidebar/main.js' %}"></script>
      <!-- Owlcarousel JS -->
      <script src="{% static 'assets/vendors/owl_carousel/owl.carousel.min.js' %}"></script>
      <!-- Stellar JS-->
      <!-- Theme JS -->
      <script src="{% static 'assets/js/theme.min.js' %}"></script>
      
   </body>
</html>